# Makefile.in generated by automake 1.9.6 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004, 2005  Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



#
# This file is released under the terms of the Artistic License.
# Please see the file LICENSE, included in this package, for details.
#
# Copyright (C) 2005 Mark Wong & Open Source Development Labs, Inc.
#
srcdir = .
top_srcdir = .

pkgdatadir = $(datadir)/dbt3
pkglibdir = $(libdir)/dbt3
pkgincludedir = $(includedir)/dbt3
top_builddir = .
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
INSTALL = /usr/bin/install -c
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = x86_64-unknown-linux-gnu
host_triplet = x86_64-unknown-linux-gnu
DIST_COMMON = README $(am__configure_deps) $(srcdir)/Makefile.am \
	$(srcdir)/Makefile.in $(top_srcdir)/configure \
	$(top_srcdir)/data_collect/sapdb/dbt3_stats.sh.in \
	$(top_srcdir)/data_collect/sapdb/power_test_stats.sh.in \
	$(top_srcdir)/data_collect/sapdb/single_query_stats.sh.in \
	$(top_srcdir)/data_collect/sapdb/throughput_query_stats.sh.in \
	$(top_srcdir)/data_collect/sapdb/throughput_test_stats.sh.in \
	$(top_srcdir)/dbdriver/scripts/sapdb/explain_power_query.sh.in \
	$(top_srcdir)/dbdriver/scripts/sapdb/explain_single_query.sh.in \
	$(top_srcdir)/dbdriver/scripts/sapdb/run_dbt3.sh.in \
	$(top_srcdir)/dbdriver/scripts/sapdb/run_load_test.sh.in \
	$(top_srcdir)/dbdriver/scripts/sapdb/run_perf_test.sh.in \
	$(top_srcdir)/dbdriver/scripts/sapdb/run_power_query.sh.in \
	$(top_srcdir)/dbdriver/scripts/sapdb/run_power_test.sh.in \
	$(top_srcdir)/dbdriver/scripts/sapdb/run_refresh_stream.sh.in \
	$(top_srcdir)/dbdriver/scripts/sapdb/run_rf1.sh.in \
	$(top_srcdir)/dbdriver/scripts/sapdb/run_rf2.sh.in \
	$(top_srcdir)/dbdriver/scripts/sapdb/run_single_query.sh.in \
	$(top_srcdir)/dbdriver/scripts/sapdb/run_throughput_query.sh.in \
	$(top_srcdir)/dbdriver/scripts/sapdb/run_throughput_test.sh.in \
	$(top_srcdir)/scripts/dbt3_profile.in \
	$(top_srcdir)/scripts/gen_data.sh.in \
	$(top_srcdir)/scripts/gen_html.sh.in \
	$(top_srcdir)/scripts/get_composite.sh.in \
	$(top_srcdir)/scripts/get_config.sh.in \
	$(top_srcdir)/scripts/ingres/clear-time-statistics.sh.in \
	$(top_srcdir)/scripts/ingres/create_db.sh.in \
	$(top_srcdir)/scripts/ingres/create_fk.sh.in \
	$(top_srcdir)/scripts/ingres/create_indexes.sh.in \
	$(top_srcdir)/scripts/ingres/create_si.sh.in \
	$(top_srcdir)/scripts/ingres/create_tables.sh.in \
	$(top_srcdir)/scripts/ingres/drop_db.sh.in \
	$(top_srcdir)/scripts/ingres/drop_tables.sh.in \
	$(top_srcdir)/scripts/ingres/get_query_plan.sh.in \
	$(top_srcdir)/scripts/ingres/grant.sh.in \
	$(top_srcdir)/scripts/ingres/ingres_profile.in \
	$(top_srcdir)/scripts/ingres/load_test.sh.in \
	$(top_srcdir)/scripts/ingres/location_names.template.in \
	$(top_srcdir)/scripts/ingres/modify_tables.sh.in \
	$(top_srcdir)/scripts/ingres/power_test.sh.in \
	$(top_srcdir)/scripts/ingres/record_end.sh.in \
	$(top_srcdir)/scripts/ingres/record_start.sh.in \
	$(top_srcdir)/scripts/ingres/run_power_query.sh.in \
	$(top_srcdir)/scripts/ingres/run_rf1.sh.in \
	$(top_srcdir)/scripts/ingres/run_rf2.sh.in \
	$(top_srcdir)/scripts/ingres/run_throughput_stream.sh.in \
	$(top_srcdir)/scripts/ingres/secondary_list.in \
	$(top_srcdir)/scripts/ingres/sort_flat_files.sh.in \
	$(top_srcdir)/scripts/ingres/sort_param.in \
	$(top_srcdir)/scripts/ingres/start_db.sh.in \
	$(top_srcdir)/scripts/ingres/stop_db.sh.in \
	$(top_srcdir)/scripts/ingres/throughput_test.sh.in \
	$(top_srcdir)/scripts/ingres/update_statistics.sh.in \
	$(top_srcdir)/scripts/init_seed.sh.in \
	$(top_srcdir)/scripts/pgsql/clear-time-statistics.sh.in \
	$(top_srcdir)/scripts/pgsql/create_db.sh.in \
	$(top_srcdir)/scripts/pgsql/create_indexes.sh.in \
	$(top_srcdir)/scripts/pgsql/create_tables.sh.in \
	$(top_srcdir)/scripts/pgsql/db_stats.sh.in \
	$(top_srcdir)/scripts/pgsql/drop_db.sh.in \
	$(top_srcdir)/scripts/pgsql/drop_tables.sh.in \
	$(top_srcdir)/scripts/pgsql/get_query_plan.sh.in \
	$(top_srcdir)/scripts/pgsql/get_version.sh.in \
	$(top_srcdir)/scripts/pgsql/grant.sh.in \
	$(top_srcdir)/scripts/pgsql/load_test.sh.in \
	$(top_srcdir)/scripts/pgsql/pgsql_profile.in \
	$(top_srcdir)/scripts/pgsql/power_test.sh.in \
	$(top_srcdir)/scripts/pgsql/q_time.sh.in \
	$(top_srcdir)/scripts/pgsql/record_end.sh.in \
	$(top_srcdir)/scripts/pgsql/record_start.sh.in \
	$(top_srcdir)/scripts/pgsql/run_power_query.sh.in \
	$(top_srcdir)/scripts/pgsql/run_rf1.sh.in \
	$(top_srcdir)/scripts/pgsql/run_rf2.sh.in \
	$(top_srcdir)/scripts/pgsql/run_throughput_stream.sh.in \
	$(top_srcdir)/scripts/pgsql/start_db.sh.in \
	$(top_srcdir)/scripts/pgsql/stop_db.sh.in \
	$(top_srcdir)/scripts/pgsql/throughput_stream_wrapper.sh.in \
	$(top_srcdir)/scripts/pgsql/throughput_test.sh.in \
	$(top_srcdir)/scripts/pgsql/update_statistics.sh.in \
	$(top_srcdir)/scripts/run_workload.sh.in \
	$(top_srcdir)/scripts/sapdb/backup_db.sh.in \
	$(top_srcdir)/scripts/sapdb/build_db.sh.in \
	$(top_srcdir)/scripts/sapdb/create_db.sh.in \
	$(top_srcdir)/scripts/sapdb/create_indexes.sh.in \
	$(top_srcdir)/scripts/sapdb/create_tables.sh.in \
	$(top_srcdir)/scripts/sapdb/drop_tables.sh.in \
	$(top_srcdir)/scripts/sapdb/load_db.sh.in \
	$(top_srcdir)/scripts/sapdb/restore_db.sh.in \
	$(top_srcdir)/scripts/sapdb/sapdb_profile.in \
	$(top_srcdir)/scripts/sapdb/update_statistics.sh.in \
	$(top_srcdir)/tpch_tools/Makefile.in AUTHORS COPYING ChangeLog \
	INSTALL NEWS config.guess config.sub depcomp install-sh \
	missing
subdir = .
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno configure.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_CLEAN_FILES = scripts/pgsql/clear-time-statistics.sh \
	scripts/pgsql/get_query_plan.sh scripts/pgsql/get_version.sh \
	scripts/pgsql/run_power_query.sh scripts/pgsql/run_rf1.sh \
	scripts/pgsql/run_rf2.sh \
	scripts/pgsql/run_throughput_stream.sh \
	scripts/pgsql/create_db.sh scripts/pgsql/create_indexes.sh \
	scripts/pgsql/create_tables.sh scripts/pgsql/db_stats.sh \
	scripts/pgsql/drop_db.sh scripts/pgsql/drop_tables.sh \
	scripts/pgsql/grant.sh scripts/pgsql/pgsql_profile \
	scripts/pgsql/q_time.sh scripts/pgsql/start_db.sh \
	scripts/pgsql/stop_db.sh scripts/pgsql/update_statistics.sh \
	scripts/pgsql/load_test.sh scripts/pgsql/power_test.sh \
	scripts/pgsql/throughput_test.sh \
	scripts/pgsql/throughput_stream_wrapper.sh \
	scripts/pgsql/record_end.sh scripts/pgsql/record_start.sh \
	data_collect/sapdb/dbt3_stats.sh \
	data_collect/sapdb/power_test_stats.sh \
	data_collect/sapdb/single_query_stats.sh \
	data_collect/sapdb/throughput_query_stats.sh \
	data_collect/sapdb/throughput_test_stats.sh \
	dbdriver/scripts/sapdb/explain_single_query.sh \
	dbdriver/scripts/sapdb/explain_power_query.sh \
	dbdriver/scripts/sapdb/run_dbt3.sh \
	dbdriver/scripts/sapdb/run_load_test.sh \
	dbdriver/scripts/sapdb/run_single_query.sh \
	dbdriver/scripts/sapdb/run_perf_test.sh \
	dbdriver/scripts/sapdb/run_power_query.sh \
	dbdriver/scripts/sapdb/run_power_test.sh \
	dbdriver/scripts/sapdb/run_refresh_stream.sh \
	dbdriver/scripts/sapdb/run_rf1.sh \
	dbdriver/scripts/sapdb/run_rf2.sh \
	dbdriver/scripts/sapdb/run_throughput_query.sh \
	dbdriver/scripts/sapdb/run_throughput_test.sh \
	scripts/sapdb/backup_db.sh scripts/sapdb/build_db.sh \
	scripts/sapdb/create_db.sh scripts/sapdb/create_indexes.sh \
	scripts/sapdb/create_tables.sh scripts/sapdb/drop_tables.sh \
	scripts/sapdb/load_db.sh scripts/sapdb/restore_db.sh \
	scripts/sapdb/sapdb_profile scripts/sapdb/update_statistics.sh \
	scripts/ingres/sort_param scripts/ingres/secondary_list \
	scripts/ingres/location_names.template \
	scripts/ingres/sort_flat_files.sh \
	scripts/ingres/modify_tables.sh \
	scripts/ingres/clear-time-statistics.sh \
	scripts/ingres/create_db.sh scripts/ingres/create_indexes.sh \
	scripts/ingres/create_fk.sh scripts/ingres/create_si.sh \
	scripts/ingres/create_tables.sh scripts/ingres/drop_db.sh \
	scripts/ingres/drop_tables.sh scripts/ingres/grant.sh \
	scripts/ingres/ingres_profile scripts/ingres/start_db.sh \
	scripts/ingres/stop_db.sh scripts/ingres/update_statistics.sh \
	scripts/ingres/load_test.sh scripts/ingres/power_test.sh \
	scripts/ingres/record_end.sh scripts/ingres/record_start.sh \
	scripts/ingres/get_query_plan.sh scripts/ingres/run_rf1.sh \
	scripts/ingres/run_rf2.sh scripts/ingres/run_power_query.sh \
	scripts/ingres/throughput_test.sh \
	scripts/ingres/run_throughput_stream.sh \
	scripts/dbt3_profile scripts/get_composite.sh \
	scripts/get_config.sh scripts/gen_data.sh scripts/gen_html.sh \
	scripts/run_workload.sh scripts/init_seed.sh \
	tpch_tools/Makefile
depcomp =
am__depfiles_maybe =
SOURCES =
DIST_SOURCES =
RECURSIVE_TARGETS = all-recursive check-recursive dvi-recursive \
	html-recursive info-recursive install-data-recursive \
	install-exec-recursive install-info-recursive \
	install-recursive installcheck-recursive installdirs-recursive \
	pdf-recursive ps-recursive uninstall-info-recursive \
	uninstall-recursive
ETAGS = etags
CTAGS = ctags
DIST_SUBDIRS = $(SUBDIRS)
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  { test ! -d $(distdir) \
    || { find $(distdir) -type d ! -perm -200 -exec chmod u+w {} ';' \
         && rm -fr $(distdir); }; }
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
distuninstallcheck_listfiles = find . -type f -print
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /root/benchmark/dbt3-ingres/missing --run aclocal-1.9
AMDEP_FALSE = #
AMDEP_TRUE = 
AMTAR = ${SHELL} /root/benchmark/dbt3-ingres/missing --run tar
AUTOCONF = ${SHELL} /root/benchmark/dbt3-ingres/missing --run autoconf
AUTOHEADER = ${SHELL} /root/benchmark/dbt3-ingres/missing --run autoheader
AUTOMAKE = ${SHELL} /root/benchmark/dbt3-ingres/missing --run automake-1.9
AWK = gawk
BC = /usr/bin/bc
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -Wall -g -O2
CPP = gcc -E
CPPFLAGS = 
CREATEDB = 
CYGPATH_W = echo
DATABASE_TO_USE = 
DEFS = -DPACKAGE_NAME=\"dbt3\" -DPACKAGE_TARNAME=\"dbt3\" -DPACKAGE_VERSION=\"1.10\" -DPACKAGE_STRING=\"dbt3\ 1.10\" -DPACKAGE_BUGREPORT=\"osdldbt-general@lists.sourceforge.net\" -DPACKAGE_URL=\"\" -DPACKAGE=\"dbt3\" -DVERSION=\"1.10\" -DSTDC_HEADERS=1 -DHAVE_SYS_WAIT_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_STRINGS_H=1 -DHAVE_SYS_TIME_H=1 -DTIME_WITH_SYS_TIME=1 -DHAVE_LIBM=1 -DWORKLOAD=\"TPCH\" -DTPCH=1
DEPDIR = .deps
DESTROYDB = 
DROPDB = 
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /bin/grep -E
EXEEXT = 
GAWK = /usr/bin/gawk
GCC = yes
GREP = /bin/grep
INGSTART = 
INGSTATUS = 
INGSTOP = 
INITDB = 
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = ${SHELL} $(install_sh) -c -s
IOSTAT = /usr/bin/iostat
LDFLAGS = 
LIBOBJS = 
LIBS = -lm 
LTLIBOBJS = 
MAKEINFO = ${SHELL} /root/benchmark/dbt3-ingres/missing --run makeinfo
MYSQLIMPORT = 
MYSQL_ADMIN = 
MYSQL_BASEDIR = 
MYSQL_BASEDIR_CNF = 
MYSQL_CONFIG = 
MYSQL_DATADIR = 
MYSQL_ENGINE = 
MYSQL_ENGINE_TUNING = 
MYSQL_PID = 
MYSQL_SOCK = 
OBJEXT = o
OPTIMIZEDB = 
OS_HOST = linux
PACKAGE = dbt3
PACKAGE_BUGREPORT = osdldbt-general@lists.sourceforge.net
PACKAGE_NAME = dbt3
PACKAGE_STRING = dbt3 1.10
PACKAGE_TARNAME = dbt3
PACKAGE_URL = 
PACKAGE_VERSION = 1.10
PATH_SEPARATOR = :
PG_CONFIG = 
PG_CTL = 
PSQL = 
SAR = /usr/bin/sar
SET_MAKE = 
SHELL = /bin/sh
SQL = 
STATDUMP = 
STRIP = 
TOPDIR = /root/benchmark/dbt3-ingres
VACUUMDB = 
VERSION = 1.10
VMSTAT = /usr/bin/vmstat
ac_ct_CC = gcc
am__fastdepCC_FALSE = #
am__fastdepCC_TRUE = 
am__include = include
am__leading_dot = .
am__quote = 
am__tar = ${AMTAR} chof - "$$tardir"
am__untar = ${AMTAR} xf -
bindir = ${exec_prefix}/bin
build = x86_64-unknown-linux-gnu
build_alias = 
build_cpu = x86_64
build_os = linux-gnu
build_vendor = unknown
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host = x86_64-unknown-linux-gnu
host_alias = 
host_cpu = x86_64
host_os = linux-gnu
host_vendor = unknown
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = /root/benchmark/dbt3-ingres/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = mkdir -p --
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
sysconfdir = ${prefix}/etc
target_alias = 
AUTOMAKE_OPTIONS = no-dependencies
SUBDIRS = src tpch_tools 
EXTRA_DIST = \
             doc/Makefile \
             doc/dbt3-architecture.sxw \
             doc/dbt3-implement.sxw \
             doc/dbt3-tpch.sxw \
             doc/dbt3-user.tex \
             doc/dbt3-user.pdf \
             doc/pgsql/dbt3-sizing-pg.sxc \
             doc/pgsql/dbt3-user-manual-pg.sxw \
             doc/sapdb/dbt3-sizing.sxc \
             doc/sapdb/dbt3-user-manual.sxw \
             perlmodules/Data_report.pm \
             queries/pgsql/1.sql \
             queries/pgsql/10.sql \
             queries/pgsql/11.sql \
             queries/pgsql/12.sql \
             queries/pgsql/13.sql \
             queries/pgsql/14.sql \
             queries/pgsql/15.sql \
             queries/pgsql/16.sql \
             queries/pgsql/17.sql \
             queries/pgsql/18.sql \
             queries/pgsql/19.sql \
             queries/pgsql/2.sql \
             queries/pgsql/20.sql \
             queries/pgsql/21.sql \
             queries/pgsql/22.sql \
             queries/pgsql/3.sql \
             queries/pgsql/4.sql \
             queries/pgsql/5.sql \
             queries/pgsql/6.sql \
             queries/pgsql/7.sql \
             queries/pgsql/8.sql \
             queries/pgsql/9.sql \
             queries/mysql/1.sql \
             queries/mysql/10.sql \
             queries/mysql/11.sql \
             queries/mysql/12.sql \
             queries/mysql/13.sql \
             queries/mysql/14.sql \
             queries/mysql/15.sql \
             queries/mysql/16.sql \
             queries/mysql/17.sql \
             queries/mysql/18.sql \
             queries/mysql/19.sql \
             queries/mysql/2.sql \
             queries/mysql/20.sql \
             queries/mysql/21.sql \
             queries/mysql/22.sql \
             queries/mysql/3.sql \
             queries/mysql/4.sql \
             queries/mysql/5.sql \
             queries/mysql/6.sql \
             queries/mysql/7.sql \
             queries/mysql/8.sql \
             queries/mysql/9.sql \
             queries/mysql/ddl \
             queries/mysql/ddl/part.sql \
             queries/mysql/ddl/region.sql \
             queries/mysql/ddl/customer.sql \
             queries/mysql/ddl/orders.sql \
             queries/mysql/ddl/partsupp.sql \
             queries/mysql/ddl/nation.sql \
             queries/mysql/ddl/supplier.sql \
             queries/mysql/ddl/lineitem.sql \
             queries/mysql/ddl/power.sql \
             queries/mysql/dll/create_indexes.sql \
             queries/mysql/ddl/nitro \
             queries/mysql/ddl/nitro/part.sql \
             queries/mysql/ddl/nitro/region.sql \
             queries/mysql/ddl/nitro/customer.sql \
             queries/mysql/ddl/nitro/orders.sql \
             queries/mysql/ddl/nitro/partsupp.sql \
             queries/mysql/ddl/nitro/nation.sql \
             queries/mysql/ddl/nitro/supplier.sql \
             queries/mysql/ddl/nitro/lineitem.sql \
             queries/sapdb/1.sql \
             queries/sapdb/10.sql \
             queries/sapdb/11.sql \
             queries/sapdb/12.sql \
             queries/sapdb/13.sql \
             queries/sapdb/14.sql \
             queries/sapdb/15.sql \
             queries/sapdb/16.sql \
             queries/sapdb/17.sql \
             queries/sapdb/18.sql \
             queries/sapdb/18rewrite.sql \
             queries/sapdb/19.sql \
             queries/sapdb/19rewrite.sql \
             queries/sapdb/2.sql \
             queries/sapdb/20.sql \
             queries/sapdb/20rewrite.sql \
             queries/sapdb/21.sql \
             queries/sapdb/22.sql \
             queries/sapdb/22rewrite.sql \
             queries/sapdb/3.sql \
             queries/sapdb/4.sql \
             queries/sapdb/5.sql \
             queries/sapdb/6.sql \
             queries/sapdb/7.sql \
             queries/sapdb/8.sql \
             queries/sapdb/9.sql \
             queries/ingres/1.sql \
             queries/ingres/10.sql \
             queries/ingres/11.sql \
             queries/ingres/12.sql \
             queries/ingres/13.sql \
             queries/ingres/14.sql \
             queries/ingres/15.sql \
             queries/ingres/16.sql \
             queries/ingres/17.sql \
             queries/ingres/18.sql \
             queries/ingres/19.sql \
             queries/ingres/2.sql \
             queries/ingres/20.sql \
             queries/ingres/21.sql \
             queries/ingres/22.sql \
             queries/ingres/3.sql \
             queries/ingres/4.sql \
             queries/ingres/5.sql \
             queries/ingres/6.sql \
             queries/ingres/7.sql \
             queries/ingres/8.sql \
             queries/ingres/9.sql \
             scripts/vmplot.sh \
             scripts/graph_query_time.pl \
             scripts/pgsql/analyze_stats.pl \
             scripts/pgsql/get_power.pl \
             scripts/pgsql/get_throughput.sh \
             scripts/mysql/analyze_stats.pl \
             scripts/mysql/clear-time-statistics.sh \
             scripts/mysql/create_db.sh \
             scripts/mysql/create_indexes.sh \
             scripts/mysql/create_tables.sh \
             scripts/mysql/drop_db.sh \
             scripts/mysql/drop_tables.sh \
             scripts/mysql/get_query_plan.sh \
             scripts/mysql/get_version.sh \
             scripts/mysql/grant.sh \
             scripts/mysql/grant.sql \
             scripts/mysql/init_db.sh \
             scripts/mysql/lockfile.sh \
             scripts/mysql/load_test.sh \
             scripts/mysql/mysql_profile \
             scripts/mysql/ordered_sets \
             scripts/mysql/power_test.sh \
             scripts/mysql/q_time.sh \
             scripts/mysql/record_end.sh \
             scripts/mysql/record_start.sh \
             scripts/mysql/run_power_query.sh \
             scripts/mysql/run_rf1.sh \
             scripts/mysql/run_rf2.sh \
             scripts/mysql/run_throughput_stream.sh \
             scripts/mysql/sort_flat_files.sh \
             scripts/mysql/sort_param \
             scripts/mysql/start_db.sh \
             scripts/mysql/stop_db.sh \
             scripts/mysql/throughput_test.sh \
             scripts/mysql/timeout.sh \
             scripts/mysql/timeout.awk \
             scripts/mysql/update_statistics.sh \
             scripts/ingres/ddl/customer.sql \
             scripts/ingres/ddl/time_statistics.sql \
             scripts/ingres/ddl/supplier.sql \
             scripts/ingres/ddl/region.sql \
             scripts/ingres/ddl/partsupp.sql \
             scripts/ingres/ddl/part.sql \
             scripts/ingres/ddl/orders.sql \
             scripts/ingres/ddl/nation.sql \
             scripts/ingres/ddl/lineitem.sql \
             scripts/ingres/ddl/create_pk.sql \
             scripts/ingres/ddl/create_fk.sql \
             scripts/ingres/ddl/modify_tables.sql \
             scripts/ingres/ddl/grant.sql \
             scripts/ingres/import/header \
             scripts/ingres/import/part.sql \
             scripts/ingres/import/partsupp.sql \
             scripts/ingres/import/lineitem.sql \
             scripts/ingres/import/orders.sql \
             scripts/ingres/import/supplier.sql \
             scripts/ingres/import/customer.sql \
             scripts/ingres/import/nation.sql \
             scripts/ingres/import/region.sql \
             scripts/ingres/get_power_metric.awk 

all: all-recursive

.SUFFIXES:
am--refresh:
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --gnu '; \
	      cd $(srcdir) && $(AUTOMAKE) --gnu  \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --gnu  Makefile'; \
	cd $(top_srcdir) && \
	  $(AUTOMAKE) --gnu  Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	cd $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	cd $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
scripts/pgsql/clear-time-statistics.sh: $(top_builddir)/config.status $(top_srcdir)/scripts/pgsql/clear-time-statistics.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/pgsql/get_query_plan.sh: $(top_builddir)/config.status $(top_srcdir)/scripts/pgsql/get_query_plan.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/pgsql/get_version.sh: $(top_builddir)/config.status $(top_srcdir)/scripts/pgsql/get_version.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/pgsql/run_power_query.sh: $(top_builddir)/config.status $(top_srcdir)/scripts/pgsql/run_power_query.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/pgsql/run_rf1.sh: $(top_builddir)/config.status $(top_srcdir)/scripts/pgsql/run_rf1.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/pgsql/run_rf2.sh: $(top_builddir)/config.status $(top_srcdir)/scripts/pgsql/run_rf2.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/pgsql/run_throughput_stream.sh: $(top_builddir)/config.status $(top_srcdir)/scripts/pgsql/run_throughput_stream.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/pgsql/create_db.sh: $(top_builddir)/config.status $(top_srcdir)/scripts/pgsql/create_db.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/pgsql/create_indexes.sh: $(top_builddir)/config.status $(top_srcdir)/scripts/pgsql/create_indexes.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/pgsql/create_tables.sh: $(top_builddir)/config.status $(top_srcdir)/scripts/pgsql/create_tables.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/pgsql/db_stats.sh: $(top_builddir)/config.status $(top_srcdir)/scripts/pgsql/db_stats.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/pgsql/drop_db.sh: $(top_builddir)/config.status $(top_srcdir)/scripts/pgsql/drop_db.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/pgsql/drop_tables.sh: $(top_builddir)/config.status $(top_srcdir)/scripts/pgsql/drop_tables.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/pgsql/grant.sh: $(top_builddir)/config.status $(top_srcdir)/scripts/pgsql/grant.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/pgsql/pgsql_profile: $(top_builddir)/config.status $(top_srcdir)/scripts/pgsql/pgsql_profile.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/pgsql/q_time.sh: $(top_builddir)/config.status $(top_srcdir)/scripts/pgsql/q_time.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/pgsql/start_db.sh: $(top_builddir)/config.status $(top_srcdir)/scripts/pgsql/start_db.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/pgsql/stop_db.sh: $(top_builddir)/config.status $(top_srcdir)/scripts/pgsql/stop_db.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/pgsql/update_statistics.sh: $(top_builddir)/config.status $(top_srcdir)/scripts/pgsql/update_statistics.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/pgsql/load_test.sh: $(top_builddir)/config.status $(top_srcdir)/scripts/pgsql/load_test.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/pgsql/power_test.sh: $(top_builddir)/config.status $(top_srcdir)/scripts/pgsql/power_test.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/pgsql/throughput_test.sh: $(top_builddir)/config.status $(top_srcdir)/scripts/pgsql/throughput_test.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/pgsql/throughput_stream_wrapper.sh: $(top_builddir)/config.status $(top_srcdir)/scripts/pgsql/throughput_stream_wrapper.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/pgsql/record_end.sh: $(top_builddir)/config.status $(top_srcdir)/scripts/pgsql/record_end.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/pgsql/record_start.sh: $(top_builddir)/config.status $(top_srcdir)/scripts/pgsql/record_start.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
data_collect/sapdb/dbt3_stats.sh: $(top_builddir)/config.status $(top_srcdir)/data_collect/sapdb/dbt3_stats.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
data_collect/sapdb/power_test_stats.sh: $(top_builddir)/config.status $(top_srcdir)/data_collect/sapdb/power_test_stats.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
data_collect/sapdb/single_query_stats.sh: $(top_builddir)/config.status $(top_srcdir)/data_collect/sapdb/single_query_stats.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
data_collect/sapdb/throughput_query_stats.sh: $(top_builddir)/config.status $(top_srcdir)/data_collect/sapdb/throughput_query_stats.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
data_collect/sapdb/throughput_test_stats.sh: $(top_builddir)/config.status $(top_srcdir)/data_collect/sapdb/throughput_test_stats.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
dbdriver/scripts/sapdb/explain_single_query.sh: $(top_builddir)/config.status $(top_srcdir)/dbdriver/scripts/sapdb/explain_single_query.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
dbdriver/scripts/sapdb/explain_power_query.sh: $(top_builddir)/config.status $(top_srcdir)/dbdriver/scripts/sapdb/explain_power_query.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
dbdriver/scripts/sapdb/run_dbt3.sh: $(top_builddir)/config.status $(top_srcdir)/dbdriver/scripts/sapdb/run_dbt3.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
dbdriver/scripts/sapdb/run_load_test.sh: $(top_builddir)/config.status $(top_srcdir)/dbdriver/scripts/sapdb/run_load_test.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
dbdriver/scripts/sapdb/run_single_query.sh: $(top_builddir)/config.status $(top_srcdir)/dbdriver/scripts/sapdb/run_single_query.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
dbdriver/scripts/sapdb/run_perf_test.sh: $(top_builddir)/config.status $(top_srcdir)/dbdriver/scripts/sapdb/run_perf_test.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
dbdriver/scripts/sapdb/run_power_query.sh: $(top_builddir)/config.status $(top_srcdir)/dbdriver/scripts/sapdb/run_power_query.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
dbdriver/scripts/sapdb/run_power_test.sh: $(top_builddir)/config.status $(top_srcdir)/dbdriver/scripts/sapdb/run_power_test.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
dbdriver/scripts/sapdb/run_refresh_stream.sh: $(top_builddir)/config.status $(top_srcdir)/dbdriver/scripts/sapdb/run_refresh_stream.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
dbdriver/scripts/sapdb/run_rf1.sh: $(top_builddir)/config.status $(top_srcdir)/dbdriver/scripts/sapdb/run_rf1.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
dbdriver/scripts/sapdb/run_rf2.sh: $(top_builddir)/config.status $(top_srcdir)/dbdriver/scripts/sapdb/run_rf2.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
dbdriver/scripts/sapdb/run_throughput_query.sh: $(top_builddir)/config.status $(top_srcdir)/dbdriver/scripts/sapdb/run_throughput_query.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
dbdriver/scripts/sapdb/run_throughput_test.sh: $(top_builddir)/config.status $(top_srcdir)/dbdriver/scripts/sapdb/run_throughput_test.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/sapdb/backup_db.sh: $(top_builddir)/config.status $(top_srcdir)/scripts/sapdb/backup_db.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/sapdb/build_db.sh: $(top_builddir)/config.status $(top_srcdir)/scripts/sapdb/build_db.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/sapdb/create_db.sh: $(top_builddir)/config.status $(top_srcdir)/scripts/sapdb/create_db.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/sapdb/create_indexes.sh: $(top_builddir)/config.status $(top_srcdir)/scripts/sapdb/create_indexes.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/sapdb/create_tables.sh: $(top_builddir)/config.status $(top_srcdir)/scripts/sapdb/create_tables.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/sapdb/drop_tables.sh: $(top_builddir)/config.status $(top_srcdir)/scripts/sapdb/drop_tables.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/sapdb/load_db.sh: $(top_builddir)/config.status $(top_srcdir)/scripts/sapdb/load_db.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/sapdb/restore_db.sh: $(top_builddir)/config.status $(top_srcdir)/scripts/sapdb/restore_db.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/sapdb/sapdb_profile: $(top_builddir)/config.status $(top_srcdir)/scripts/sapdb/sapdb_profile.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/sapdb/update_statistics.sh: $(top_builddir)/config.status $(top_srcdir)/scripts/sapdb/update_statistics.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/ingres/sort_param: $(top_builddir)/config.status $(top_srcdir)/scripts/ingres/sort_param.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/ingres/secondary_list: $(top_builddir)/config.status $(top_srcdir)/scripts/ingres/secondary_list.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/ingres/location_names.template: $(top_builddir)/config.status $(top_srcdir)/scripts/ingres/location_names.template.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/ingres/sort_flat_files.sh: $(top_builddir)/config.status $(top_srcdir)/scripts/ingres/sort_flat_files.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/ingres/modify_tables.sh: $(top_builddir)/config.status $(top_srcdir)/scripts/ingres/modify_tables.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/ingres/clear-time-statistics.sh: $(top_builddir)/config.status $(top_srcdir)/scripts/ingres/clear-time-statistics.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/ingres/create_db.sh: $(top_builddir)/config.status $(top_srcdir)/scripts/ingres/create_db.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/ingres/create_indexes.sh: $(top_builddir)/config.status $(top_srcdir)/scripts/ingres/create_indexes.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/ingres/create_fk.sh: $(top_builddir)/config.status $(top_srcdir)/scripts/ingres/create_fk.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/ingres/create_si.sh: $(top_builddir)/config.status $(top_srcdir)/scripts/ingres/create_si.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/ingres/create_tables.sh: $(top_builddir)/config.status $(top_srcdir)/scripts/ingres/create_tables.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/ingres/drop_db.sh: $(top_builddir)/config.status $(top_srcdir)/scripts/ingres/drop_db.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/ingres/drop_tables.sh: $(top_builddir)/config.status $(top_srcdir)/scripts/ingres/drop_tables.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/ingres/grant.sh: $(top_builddir)/config.status $(top_srcdir)/scripts/ingres/grant.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/ingres/ingres_profile: $(top_builddir)/config.status $(top_srcdir)/scripts/ingres/ingres_profile.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/ingres/start_db.sh: $(top_builddir)/config.status $(top_srcdir)/scripts/ingres/start_db.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/ingres/stop_db.sh: $(top_builddir)/config.status $(top_srcdir)/scripts/ingres/stop_db.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/ingres/update_statistics.sh: $(top_builddir)/config.status $(top_srcdir)/scripts/ingres/update_statistics.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/ingres/load_test.sh: $(top_builddir)/config.status $(top_srcdir)/scripts/ingres/load_test.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/ingres/power_test.sh: $(top_builddir)/config.status $(top_srcdir)/scripts/ingres/power_test.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/ingres/record_end.sh: $(top_builddir)/config.status $(top_srcdir)/scripts/ingres/record_end.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/ingres/record_start.sh: $(top_builddir)/config.status $(top_srcdir)/scripts/ingres/record_start.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/ingres/get_query_plan.sh: $(top_builddir)/config.status $(top_srcdir)/scripts/ingres/get_query_plan.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/ingres/run_rf1.sh: $(top_builddir)/config.status $(top_srcdir)/scripts/ingres/run_rf1.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/ingres/run_rf2.sh: $(top_builddir)/config.status $(top_srcdir)/scripts/ingres/run_rf2.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/ingres/run_power_query.sh: $(top_builddir)/config.status $(top_srcdir)/scripts/ingres/run_power_query.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/ingres/throughput_test.sh: $(top_builddir)/config.status $(top_srcdir)/scripts/ingres/throughput_test.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/ingres/run_throughput_stream.sh: $(top_builddir)/config.status $(top_srcdir)/scripts/ingres/run_throughput_stream.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/dbt3_profile: $(top_builddir)/config.status $(top_srcdir)/scripts/dbt3_profile.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/get_composite.sh: $(top_builddir)/config.status $(top_srcdir)/scripts/get_composite.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/get_config.sh: $(top_builddir)/config.status $(top_srcdir)/scripts/get_config.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/gen_data.sh: $(top_builddir)/config.status $(top_srcdir)/scripts/gen_data.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/gen_html.sh: $(top_builddir)/config.status $(top_srcdir)/scripts/gen_html.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/run_workload.sh: $(top_builddir)/config.status $(top_srcdir)/scripts/run_workload.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/init_seed.sh: $(top_builddir)/config.status $(top_srcdir)/scripts/init_seed.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
tpch_tools/Makefile: $(top_builddir)/config.status $(top_srcdir)/tpch_tools/Makefile.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
uninstall-info-am:

# This directory's subdirectories are mostly independent; you can cd
# into them and run `make' without going through this Makefile.
# To change the values of `make' variables: instead of editing Makefiles,
# (1) if the variable is set in `config.status', edit `config.status'
#     (which will cause the Makefiles to be regenerated when you run `make');
# (2) otherwise, pass the desired values on the `make' command line.
$(RECURSIVE_TARGETS):
	@failcom='exit 1'; \
	for f in x $$MAKEFLAGS; do \
	  case $$f in \
	    *=* | --[!k]*);; \
	    *k*) failcom='fail=yes';; \
	  esac; \
	done; \
	dot_seen=no; \
	target=`echo $@ | sed s/-recursive//`; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "."; then \
	    dot_seen=yes; \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	  || eval $$failcom; \
	done; \
	if test "$$dot_seen" = "no"; then \
	  $(MAKE) $(AM_MAKEFLAGS) "$$target-am" || exit 1; \
	fi; test -z "$$fail"

mostlyclean-recursive clean-recursive distclean-recursive \
maintainer-clean-recursive:
	@failcom='exit 1'; \
	for f in x $$MAKEFLAGS; do \
	  case $$f in \
	    *=* | --[!k]*);; \
	    *k*) failcom='fail=yes';; \
	  esac; \
	done; \
	dot_seen=no; \
	case "$@" in \
	  distclean-* | maintainer-clean-*) list='$(DIST_SUBDIRS)' ;; \
	  *) list='$(SUBDIRS)' ;; \
	esac; \
	rev=''; for subdir in $$list; do \
	  if test "$$subdir" = "."; then :; else \
	    rev="$$subdir $$rev"; \
	  fi; \
	done; \
	rev="$$rev ."; \
	target=`echo $@ | sed s/-recursive//`; \
	for subdir in $$rev; do \
	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "."; then \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	  || eval $$failcom; \
	done && test -z "$$fail"
tags-recursive:
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  test "$$subdir" = . || (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) tags); \
	done
ctags-recursive:
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  test "$$subdir" = . || (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) ctags); \
	done

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	mkid -fID $$unique
tags: TAGS

TAGS: tags-recursive $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	here=`pwd`; \
	if ($(ETAGS) --etags-include --version) >/dev/null 2>&1; then \
	  include_option=--etags-include; \
	  empty_fix=.; \
	else \
	  include_option=--include; \
	  empty_fix=; \
	fi; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    test ! -f $$subdir/TAGS || \
	      tags="$$tags $$include_option=$$here/$$subdir/TAGS"; \
	  fi; \
	done; \
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	if test -z "$(ETAGS_ARGS)$$tags$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	    $$tags $$unique; \
	fi
ctags: CTAGS
CTAGS: ctags-recursive $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(CTAGS_ARGS)$$tags$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$tags $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && cd $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) $$here

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

distdir: $(DISTFILES)
	$(am__remove_distdir)
	mkdir $(distdir)
	$(mkdir_p) $(distdir)/data_collect/sapdb $(distdir)/dbdriver/scripts/sapdb $(distdir)/doc $(distdir)/doc/pgsql $(distdir)/doc/sapdb $(distdir)/perlmodules $(distdir)/queries/ingres $(distdir)/queries/mysql $(distdir)/queries/mysql/ddl $(distdir)/queries/mysql/ddl/nitro $(distdir)/queries/mysql/dll $(distdir)/queries/pgsql $(distdir)/queries/sapdb $(distdir)/scripts $(distdir)/scripts/ingres $(distdir)/scripts/ingres/ddl $(distdir)/scripts/ingres/import $(distdir)/scripts/ingres_vectorwise $(distdir)/scripts/ingres_vectorwise/acid $(distdir)/scripts/ingres_vectorwise/acid/atom $(distdir)/scripts/ingres_vectorwise/acid/cons $(distdir)/scripts/ingres_vectorwise/acid/dur $(distdir)/scripts/ingres_vectorwise/acid/iso $(distdir)/scripts/ingres_vectorwise/ddl $(distdir)/scripts/ingres_vectorwise/import $(distdir)/scripts/ingres_vectorwise/reference/cardinality.sf1 $(distdir)/scripts/ingres_vectorwise/reference/cardinality.sf10 $(distdir)/scripts/ingres_vectorwise/reference/cardinality.sf100 $(distdir)/scripts/ingres_vectorwise/reference/cardinality.sf3 $(distdir)/scripts/ingres_vectorwise/reference/cardinality.sf30 $(distdir)/scripts/ingres_vectorwise/reference/results.sf1 $(distdir)/scripts/ingres_vectorwise/reference/results.sf10 $(distdir)/scripts/ingres_vectorwise/reference/results.sf100 $(distdir)/scripts/ingres_vectorwise/reference/results.sf3 $(distdir)/scripts/ingres_vectorwise/reference/results.sf30 $(distdir)/scripts/mysql $(distdir)/scripts/pgsql $(distdir)/scripts/sapdb $(distdir)/tpch_tools
	@srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's|.|.|g'`; \
	list='$(DISTFILES)'; for file in $$list; do \
	  case $$file in \
	    $(srcdir)/*) file=`echo "$$file" | sed "s|^$$srcdirstrip/||"`;; \
	    $(top_srcdir)/*) file=`echo "$$file" | sed "s|^$$topsrcdirstrip/|$(top_builddir)/|"`;; \
	  esac; \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  dir=`echo "$$file" | sed -e 's,/[^/]*$$,,'`; \
	  if test "$$dir" != "$$file" && test "$$dir" != "."; then \
	    dir="/$$dir"; \
	    $(mkdir_p) "$(distdir)$$dir"; \
	  else \
	    dir=''; \
	  fi; \
	  if test -d $$d/$$file; then \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -pR $(srcdir)/$$file $(distdir)$$dir || exit 1; \
	    fi; \
	    cp -pR $$d/$$file $(distdir)$$dir || exit 1; \
	  else \
	    test -f $(distdir)/$$file \
	    || cp -p $$d/$$file $(distdir)/$$file \
	    || exit 1; \
	  fi; \
	done
	list='$(DIST_SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    test -d "$(distdir)/$$subdir" \
	    || $(mkdir_p) "$(distdir)/$$subdir" \
	    || exit 1; \
	    distdir=`$(am__cd) $(distdir) && pwd`; \
	    top_distdir=`$(am__cd) $(top_distdir) && pwd`; \
	    (cd $$subdir && \
	      $(MAKE) $(AM_MAKEFLAGS) \
	        top_distdir="$$top_distdir" \
	        distdir="$$distdir/$$subdir" \
	        distdir) \
	      || exit 1; \
	  fi; \
	done
	-find $(distdir) -type d ! -perm -755 -exec chmod a+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(SHELL) $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r $(distdir)
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | bzip2 -9 -c >$(distdir).tar.bz2
	$(am__remove_distdir)

dist-tarZ: distdir
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__remove_distdir)

dist-shar: distdir
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__remove_distdir)

dist dist-all: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gunzip -c $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bunzip2 -c $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gunzip -c $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir); chmod a+w $(distdir)
	mkdir $(distdir)/_build
	mkdir $(distdir)/_inst
	chmod a-w $(distdir)
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && cd $(distdir)/_build \
	  && ../configure --srcdir=.. --prefix="$$dc_install_base" \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck
	$(am__remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e '1{h;s/./=/g;p;x;}' -e '$${p;x;}'
distuninstallcheck:
	@cd $(distuninstallcheck_dir) \
	&& test `$(distuninstallcheck_listfiles) | wc -l` -le 1 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-recursive
all-am: Makefile
installdirs: installdirs-recursive
installdirs-am:
install: install-recursive
install-exec: install-exec-recursive
install-data: install-data-recursive
uninstall: uninstall-recursive

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-recursive
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-recursive

clean-am: clean-generic mostlyclean-am

distclean: distclean-recursive
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -f Makefile
distclean-am: clean-am distclean-generic distclean-tags

dvi: dvi-recursive

dvi-am:

html: html-recursive

info: info-recursive

info-am:

install-data-am:

install-exec-am:

install-info: install-info-recursive

install-man:

installcheck-am:

maintainer-clean: maintainer-clean-recursive
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-recursive

mostlyclean-am: mostlyclean-generic

pdf: pdf-recursive

pdf-am:

ps: ps-recursive

ps-am:

uninstall-am: uninstall-info-am

uninstall-info: uninstall-info-recursive

.PHONY: $(RECURSIVE_TARGETS) CTAGS GTAGS all all-am am--refresh check \
	check-am clean clean-generic clean-recursive ctags \
	ctags-recursive dist dist-all dist-bzip2 dist-gzip dist-shar \
	dist-tarZ dist-zip distcheck distclean distclean-generic \
	distclean-recursive distclean-tags distcleancheck distdir \
	distuninstallcheck dvi dvi-am html html-am info info-am \
	install install-am install-data install-data-am install-exec \
	install-exec-am install-info install-info-am install-man \
	install-strip installcheck installcheck-am installdirs \
	installdirs-am maintainer-clean maintainer-clean-generic \
	maintainer-clean-recursive mostlyclean mostlyclean-generic \
	mostlyclean-recursive pdf pdf-am ps ps-am tags tags-recursive \
	uninstall uninstall-am uninstall-info-am

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
