-- @(#)12.sql	2.1.8.1
-- TPC-H/TPC-R Shipping Modes and Order Priority Query (Q12)
-- Functional Query Definition
-- Approved February 1998
:b
:x
:o
SELECT 
	L_SHIPMODE,
	SUM(CASE 
		WHEN O_ORDERPRIORITY = '1-URGENT' 
			OR O_ORDERPRIORITY = '2-HIGH' 
			THEN 1 
		ELSE 0 
	END) AS HIGH_LINE_COUNT, 
	SUM(CASE 
		WHEN O_ORDERPRIORITY <> '1-URGENT' 
			AND O_ORDERPRIORITY <> '2-HIGH'
			THEN 1 
		ELSE 0 
	END) AS LOW_LINE_COUNT
FROM 
	ORDERS, 
	LINEITEM
WHERE 
	O_ORDERKEY = L_ORDERKEY 
	AND L_SHIPMODE IN (':1',':2') 
	AND L_COMMITDATE < L_RECEIPTDATE 
	AND L_SHIPDATE < L_COMMITDATE 
	AND L_RECEIPTDATE >= ':3' 
	AND L_RECEIPTDATE < dateadd(yy, 1, ':3')
GROUP BY 
	L_SHIPMODE
ORDER BY 
	L_SHIPMODE
:e