-- @(#)15.sql	2.1.8.1
-- TPC-H/TPC-R Top Supplier Query (Q15)
-- Functional Query Definition
-- Approved February 1998
:b
CREATE VIEW REVENUE:s (SUPPLIER_NO, TOTAL_REVENUE) AS
	SELECT 
		L_SUPPKEY, 
		SUM(L_EXTENDEDPRICE*(1-L_DISCOUNT)) 
	FROM 
		LINEITEM
	WHERE 
		L_SHIPDATE >= ':1'
		AND L_SHIPDATE < dateadd(mm, 3, ':1')
GROUP BY 
	L_SUPPKEY
GO	
:x
:o	
SELECT 
	S_SUPPKEY,
	S_NAME,
	S_ADDRESS,
	S_PHONE,
	TOTAL_REVENUE
FROM 
	SUPPLIER, 
	REVENUE:s
WHERE 
	S_SUPPKEY = SUPPLIER_NO 
	AND TOTAL_REVENUE = ( 
		SELECT 
			MAX(TOTAL_REVENUE) 
		FROM 
			REVENUE:s
	)
ORDER BY 
	S_SUPPKEY
	
DROP VIEW REVENUE:s
:e	