-- @(#)18.sql	2.1.8.1
-- TPC-H/TPC-R Large Volume Customer Query (Q18)
-- Function Query Definition
-- Approved February 1998
:b
:x
:o
:n 100
SELECT
	C_NAME, 
	C_CUSTKEY, 
	O_ORDERKEY, 
	O_ORDERDATE, 
	O_TOTALPRICE,
	SUM(L_QUANTITY)
FROM 
	CUSTOMER, 
	ORDERS, 
	LINEITEM
WHERE 
	O_ORDERKEY IN (
		SELECT 
			L_ORDERKEY 
		FROM 
			LINEITEM 
		GROUP BY 
			L_ORDERKEY HAVING
				SUM(L_QUANTITY) > :1
	) 
	AND C_CUSTKEY = O_CUSTKEY 
	AND O_ORDERKEY = L_ORDERKEY
GROUP BY 
	C_NAME, 
	C_CUSTKEY, 
	O_ORDERKEY, 
	O_ORDERDATE, 
	O_TOTALPRICE
ORDER BY 
	O_TOTALPRICE DESC, 
	O_ORDERDATE
:e	