-- @(#)19.sql	2.1.8.1
-- TPC-H/TPC-R Discounted Revenue Query (Q19)
-- Functional Query Definition
-- Approved February 1998
:b
:x
:o
SELECT 
	SUM(L_EXTENDEDPRICE* (1 - L_DISCOUNT)) AS REVENUE
FROM 
	LINEITEM, 
	PART
WHERE (
	P_PARTKEY = L_PARTKEY 
	AND P_BRAND = ':1' 
	AND P_CONTAINER IN ( 'SM CASE', 'SM BOX', 'SM PACK', 'SM PKG') 
	AND L_QUANTITY >= :4 AND L_QUANTITY <= :4 + 10 
	AND P_SIZE BETWEEN 1 AND 5
	AND L_SHIPMODE IN ('AIR', 'AIR REG') 
	AND L_SHIPINSTRUCT = 'DELIVER IN PERSON'
	)
	OR (
	P_PARTKEY = L_PARTKEY 
	AND P_BRAND = ':2' 
	AND P_CONTAINER IN ( 'MED BAG', 'MED BOX', 'MED PKG', 'MED PACK') 
	AND L_QUANTITY >= :5 AND L_QUANTITY <= :5 + 10 
	AND P_SIZE BETWEEN 1 AND 10 
	AND L_SHIPMODE IN ('AIR', 'AIR REG') 
	AND L_SHIPINSTRUCT = 'DELIVER IN PERSON'
	) 
	OR (
	P_PARTKEY = L_PARTKEY 
	AND P_BRAND = ':3' 
	AND P_CONTAINER IN ( 'LG CASE', 'LG BOX', 'LG PACK', 'LG PKG') 
	AND L_QUANTITY >= :6 AND L_QUANTITY <= :6 + 10 
	AND P_SIZE BETWEEN 1 AND 15
	AND L_SHIPMODE IN ('AIR', 'AIR REG') 
	AND L_SHIPINSTRUCT = 'DELIVER IN PERSON'
	)
:e