-- @(#)5.sql	2.1.8.1
-- TPC-H/TPC-R Local Supplier Volume Query (Q5)
-- Functional Query Definition
-- Approved February 1998
:b
:x
:o
SELECT 
	N_NAME, 
	SUM(L_EXTENDEDPRICE*(1-L_DISCOUNT)) AS REVENUE
FROM 
	CUSTOMER, 
	ORDERS, 
	LINEITEM, 
	SUPPLIER, 
	NATION, 
	REGION
WHERE 
	C_CUSTKEY = O_CUSTKEY 
	AND L_ORDERKEY = O_ORDERKEY 
	AND L_SUPPKEY = S_SUPPKEY 
	AND C_NATIONKEY = S_NATIONKEY 
	AND S_NATIONKEY = N_NATIONKEY 
	AND N_REGIONKEY = R_REGIONKEY
	AND R_NAME = ':1' 
	AND O_ORDERDATE >= ':2' 
	AND O_ORDERDATE < DATEADD(YY, 1, ':2')
GROUP BY 
	N_NAME
ORDER BY 
	REVENUE DESC
:e